### PR TITLE
Presence Degradation Reporter

### PR DESCRIPTION
**Pull request by anyercastillo**
Introduces Presence Degradation Reporter.
Documentation can be found in the README.md

## VIDEO
https://github.com/getditto/DittoAndroidTools/assets/5747647/b2191209-9fbd-4a80-b2fb-28d16c155c80

## ARTIFACTS
Sonatype artifacts are ready for deployment. [NOT DEPLOYED YET]

Screenshot 2024-02-12 at 11 22 33 AM

### CODE REVIEW

**Comment by texasRanger09** [comment]
Would it be helpful to add a "Clear Remote Devices" button? It looks like the only way to clear the list of remote devices is to restart the app. I'm thinking this would mostly be helpful for clearing out devices that are no longer seen and you do not want them to clutter up the screen anymore.

**Comment by texasRanger09** [comment]
We should display the `peerKey` value for each device as well. This should help with debugging since that value is used in the ditto logs.

**Comment by anyercastillo** [comment]
> We should display the `peerKey` value for each device as well. This would help with debugging since that value is used in the ditto logs.

sounds like a very good idea.
thanks

**Comment by anyercastillo** [comment]
peer-key

**Review by texasRanger09 — APPROVED** [review]

**Pull request merged**
