### PR TITLE
Don't subscribe to the heartbeat collection if not publishing heartbe…

### LINKED ISSUE #73: Android - add the ability to disable heartbeat output to Ditto collection

### LINKED ISSUE #74: Android - tweaks to heartbeat collection subscription

### PR DESCRIPTION
**Pull request by texasRanger09**
fixes #73  
part of #79 
fixes #74

### CODE REVIEW

**Review by zmarkan — APPROVED** [review]
Is this because the subscription is only required for publishing heartbeats & it's not possible to publish without an ongoing subscription?

**Comment by bplattenburg** [comment]
@texasRanger09 This should close #74 , so I'll go ahead and update that to link here and add your name etc

**Review by bplattenburg — APPROVED** [review]

**Comment by okdistribute** [comment]
No a subscription is not required to publish heartbeats. I am not convinced yet that we should be subscribing to them as part of this tool since it's a side effect

**Comment by bplattenburg** [comment]
@okdistribute Any objections to merging this as-is and revisiting the subscription in #84 ?

**Comment by okdistribute** [comment]
I don't understand why it's called "publish to ditto collection" if it's a subscription - can you guys think through this feature a bit more?

**Comment by okdistribute** [comment]
Feel free to merge but yeah, it needs another look

**Comment by bplattenburg** [comment]
https://github.com/getditto/DittoAndroidTools/pull/94 will cover this as well, this can be closed after that PR is merged.

**Pull request closed without merging**
