### PR TITLE
bump export logs version

### PR DESCRIPTION
**Pull request by texasRanger09**
Bumped version and published to Maven

### CODE REVIEW

**Review by bplattenburg — APPROVED** [review]

**Review by rajramsaroop — CHANGES_REQUESTED** [review]
Need to update the README file as well

**Comment by texasRanger09** [comment]
> Need to update the README file as well

The ReadMe was not tracking latest versions. It shows the dependency information with an example version, but we have not been using that as the latest version reference. Do we want to update the ReadMe to include the latest versions for each tool?

**Comment by zmarkan** [comment]
I used to write ReadMe files with dependency versions extracted like this:

```
  implementation 'live.ditto:dittopresenceviewer:YOUR_LIBRARY_VERSION'
``` 

... And then specify the latest lib version at the top somewhere and link to GH tags/releases (if we tie to that) and/or maven central. 

Just a thought - might make maintaining a little easier?

**Review by zmarkan — APPROVED** [review]

**Comment by rajramsaroop** [comment]
> I used to write ReadMe files with dependency versions extracted like this:
> 
> ```
>   implementation 'live.ditto:dittopresenceviewer:YOUR_LIBRARY_VERSION'
> ```
> 
> ... And then specify the latest lib version at the top somewhere and link to GH tags/releases (if we tie to that) and/or maven central.
> 
> Just a thought - might make maintaining a little easier?

I like this idea since our tools are currently different versions and it would get annoying to update every time. I know most developers will know what's actually latest (if not Android studio will tell them lol) so this makes sense.

**Review by rajramsaroop — APPROVED** [review]

**Pull request merged**
